### ISSUE TITLE
\subfigure is an undefined control sequence

### ISSUE THREAD

**Issue by Cherubin7th** [JournalMLR/jmlr-style-file#3]
The guidelines I found like [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj2jaiy0K3bAhUGUBQKHaRQCy8QFggpMAA&url=https%3A%2F%2Fwww.overleaf.com%2Flatex%2Ftemplates%2Fjournal-of-machine-learning-research-jmlr-template%2Fhkgwnbykrbtb%2Fversions%2F1541.pdf&usg=AOvVaw11PEiuNoZQCybhGgtLlFPu) say to use \subfigure to create subfigures. However, I get an error when I use it:

**Undefined control sequence. \subfigure**

Why doesn't it work?

**Comment by casutton** [comment]
It's most likely that you need to include the subfigure package, i.e. \usepackage{subfigure}. This package should be included into your LaTeX distribution; this isn't to do with the JMLR style file. Hopefully you should be able to find someone local who can give you advice on using LaTeX. I hope this points you in the right direction!
